// build_manifest.js — scans the repo for .glsl shaders and writes vj/manifest.json
// Procedural shaders = root *.glsl (driven by iResolution/iTime only).
// Photo shaders = moodboard glsl that declare `sampler2D iChannel0`; paired with an image.
// Run:  node vj/build_manifest.js
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");

function walk(dir, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) {
      if (["node_modules", ".git", "vj", "__pycache__"].includes(e.name)) continue;
      walk(full, out);
    } else if (e.name.endsWith(".glsl")) {
      out.push(full);
    }
  }
  return out;
}

const rel = (p) => path.relative(ROOT, p).split(path.sep).join("/");

// preserve matte fields from a previous run (generated by generate_mattes.py)
const prevMatte = {};
try {
  const prev = JSON.parse(fs.readFileSync(path.join(__dirname, "manifest.json"), "utf8"));
  for (const s of prev.shaders || []) if (s.matte) prevMatte[s.id] = s.matte;
} catch (e) { /* no previous manifest */ }

const entries = [];
const seenPhoto = new Set(); // dedupe photo shaders by basename, prefer *_all

for (const file of walk(ROOT)) {
  const src = fs.readFileSync(file, "utf8");
  const r = rel(file);
  const base = path.basename(file, ".glsl");
  const isRoot = !r.includes("/"); // root-level *.glsl
  const isPhoto = /sampler2D\s+iChannel0/.test(src);

  if (isRoot && !isPhoto) {
    entries.push({ id: base, type: "procedural", shader: r });
  } else if (isPhoto) {
    // resolve the paired image: .../glsl/X.glsl -> .../assets/X.jpg
    const imgRel = r.replace("/glsl/", "/assets/").replace(/\.glsl$/, ".jpg");
    if (!fs.existsSync(path.join(ROOT, imgRel))) continue;
    // prefer the trippy_ornaments_all copy when duplicated
    const prev = entries.find((e) => e.id === base && e.type === "photo");
    if (prev) {
      if (r.includes("trippy_ornaments_all")) {
        prev.shader = r;
        prev.image = imgRel;
      }
      continue;
    }
    const photoEntry = { id: base, type: "photo", shader: r, image: imgRel };
    if (prevMatte[base]) photoEntry.matte = prevMatte[base];
    entries.push(photoEntry);
  }
}

entries.sort((a, b) => (a.type === b.type ? a.id.localeCompare(b.id) : a.type.localeCompare(b.type)));

const manifest = {
  generated: new Date().toISOString(),
  count: entries.length,
  procedural: entries.filter((e) => e.type === "procedural").length,
  photo: entries.filter((e) => e.type === "photo").length,
  shaders: entries,
};

fs.writeFileSync(path.join(__dirname, "manifest.json"), JSON.stringify(manifest, null, 2));
console.log(`Wrote vj/manifest.json: ${manifest.count} shaders (${manifest.procedural} procedural, ${manifest.photo} photo)`);
